name: Zajem podatkov o zamudah

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # To zagotovi pravice za pisanje neposredno v kodi
    steps:
      - name: Checkout kode
        uses: actions/checkout@v4.1.7 # Specifična podverzija

      - name: Nastavitev Python-a
        uses: actions/setup-python@v5.1.0 # Specifična podverzija
        with:
          python-version: '3.11'

      - name: Namestitev knjižnic
        run: |
          pip install requests beautifulsoup4 pandas

      - name: Zagon scraperja
        run: python scraper.py

      - name: Shranjevanje podatkov v CSV
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add zamude.csv
          git commit -m "Posodobitev zamud: $(date)" || exit 0
          git push
