name: Zajem podatkov o zamudah

on:
  schedule:
    - cron: '*/15 * * * *'  # Vsakih 15 minut
  workflow_dispatch:      # Omogoča ročni zagon

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true  # Ta vrstica odstrani opozorilo
    steps:
      - name: Checkout kode
        uses: actions/checkout@v4  # Posodobljeno z v3 na v4

      - name: Nastavitev Python-a
        uses: actions/setup-python@v5  # Posodobljeno z v4 na v5
        with:
          python-version: '3.11'   # Uporabimo novejši Python

      - name: Namestitev knjižnic
        run: |
          pip install requests beautifulsoup4 pandas

      - name: Zagon scraperja
        run: python scraper.py

      - name: Shranjevanje podatkov v CSV
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add zamude.csv
          git commit -m "Posodobitev zamud: $(date)" || exit 0
          git push
