name: Posodabljanje zamud

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout kode
        uses: actions/checkout@v4

      - name: Nastavitev Pythona
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Namestitev knjižnic
        run: pip install requests pandas

      - name: Zaženi scraper
        run: python cron.py

      - name: Shranjevanje podatkov v CSV
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git fetch origin main
          git checkout main
          git add zamude.csv
          # Dodamo čas v commit, da vidiva, če se sploh izvede
          git commit -m "Zajem podatkov: $(date)" || echo "Ni sprememb"
          git push origin main
